#!/usr/bin/env bash
#
# Re-creates the third-party files of the admin UI from pinned npm packages, so their provenance is reproducible and
# nothing is loaded from a CDN at run time:
#
#   ips/js/vue.global.prod.js        Vue 3 (MIT), the global build
#   ips/css/fonts/*.woff2            Newsreader, IBM Plex Sans, IBM Plex Mono (SIL OFL), latin + latin-ext only
#   ips/css/ips-fonts.css            the @font-face rules for them (unicode-range, so a subset loads only when needed)
#   ips/js/ips-icons.js              the Feather icons (MIT) the UI uses, as inline SVG contents (window.IPS_ICONS)
#
# Usage: tools/vendor-ui-assets.sh      (needs node and npm; run it again only to change a version or the icon list)
set -euo pipefail

VUE=3.5.43
FONTSOURCE=5.3.0
FEATHER=4.29.2
ICONS="alert-circle alert-triangle archive arrow-down arrow-up book-open check check-circle check-square chevron-down
chevron-left chevron-right clock code download edit edit-3 external-link eye file file-text filter folder
folder-plus grid hard-drive home image inbox info layers list log-out maximize-2 menu minus more-horizontal move pause
play plus refresh-cw rotate-ccw rotate-cw search shield sidebar trash-2 upload upload-cloud user users x zoom-in zoom-out"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ips="$here/ips"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
cd "$work"
npm init -y >/dev/null
npm install --silent "vue@$VUE" "@fontsource/newsreader@$FONTSOURCE" "@fontsource/ibm-plex-sans@$FONTSOURCE" \
  "@fontsource/ibm-plex-mono@$FONTSOURCE" "feather-icons@$FEATHER"

install -D -m 0644 node_modules/vue/dist/vue.global.prod.js "$ips/js/vue.global.prod.js"

mkdir -p "$ips/css/fonts"
rm -f "$ips"/css/fonts/*.woff2
LATIN='U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'
LATINEXT='U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF'
{
  echo "/* Self-hosted fonts (SIL OFL): generated by tools/vendor-ui-assets.sh. Latin and latin-ext only. */"
  for spec in "newsreader:Newsreader:400 500 600" "ibm-plex-sans:IBM Plex Sans:400 500 600" "ibm-plex-mono:IBM Plex Mono:400 500"; do
    pkg="${spec%%:*}"; rest="${spec#*:}"; family="${rest%%:*}"; weights="${rest#*:}"
    cp "node_modules/@fontsource/$pkg/LICENSE" "$ips/css/fonts/LICENSE-$pkg.txt"
    for w in $weights; do
      for subset in latin latin-ext; do
        file="$pkg-$subset-$w-normal.woff2"
        cp "node_modules/@fontsource/$pkg/files/$file" "$ips/css/fonts/$file"
        range=$LATIN; [[ $subset == latin-ext ]] && range=$LATINEXT
        printf "@font-face{font-family:'%s';font-style:normal;font-display:swap;font-weight:%s;src:url(fonts/%s) format('woff2');unicode-range:%s}\n" \
          "$family" "$w" "$file" "$range"
      done
    done
  done
} > "$ips/css/ips-fonts.css"

ICONS="$ICONS" node -e '
  const feather = require("feather-icons");
  const out = {};
  for (const name of process.env.ICONS.split(/\s+/).filter(Boolean)) {
    if (!feather.icons[name]) { console.error("unknown Feather icon: " + name); process.exit(1); }
    out[name] = feather.icons[name].contents;
  }
  const body = Object.keys(out).sort().map((k) => "  " + JSON.stringify(k) + ": " + JSON.stringify(out[k])).join(",\n");
  process.stdout.write("/* Feather icons (MIT), the ones the admin UI uses: generated by tools/vendor-ui-assets.sh. */\nwindow.IPS_ICONS = {\n" + body + "\n};\n");
' > "$ips/js/ips-icons.js"

echo "vue $VUE, fonts $FONTSOURCE, feather $FEATHER"
echo "$(ls "$ips"/css/fonts/*.woff2 | wc -l) font files, $(du -ch "$ips"/css/fonts/*.woff2 | tail -1 | cut -f1) total; $(grep -c '^  "' "$ips/js/ips-icons.js") icons"
